tap caskroom/cask
tap caskroom/fonts
tap caskroom/versions
tap homebrew/science
tap homebrew/binary
tap homebrew/versions
tap peco/peco
install git --with-brewed-openssl --with-brewed-curl --with-persistent-https
install python --with-brewed-openssl --universal --framework
install gh
install git-flow-avh
install zsh
install autojump
install coreutils
install ctags
install growly
install heroku-toolbelt
install imagemagick
install mariadb
install mongodb
install namebench
install vim
install nvm
install phantomjs
install zsh-completions
install rbenv
install reattach-to-user-namespace
install redis
install ruby-build
install ssh-copy-id
install selecta
install tmux
install tree
install wget
install javarepl
install brew-cask
install httpie
install rubocop
install peco
install pup
cask install alfred
cask alfed link
cask install qlcolorcode
cask install qlstephen
cask install qlmarkdown
cask install quicklook-json
cask install quicklook-csv
cask install betterzipql
cask install suspicious-package
cask install keyremap4macbook
cask install seil
cask install rescuetime
cask install dropbox
cask install slate
cask install gfxcardstatus
cask install flux
cask install istat-menus
cask install spotify
cask install evernote
cask install google-chrome
cask install firefox
cask install opera
cask install steam
cask install toggldesktop
cask install fluid
cask install sequel-pro
cask install iterm2
cask install sublime-text
cask install skitch
cask install sourcetree
cask install Amethyst
cask install Archiver
cask install atom
cask install lastpass-universal
cask install java
